// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: privacy/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the privacy module's genesis state.
type GenesisState struct {
	Params                 Params                  `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	SerialNumberList       []SerialNumber          `protobuf:"bytes,2,rep,name=serialNumberList,proto3" json:"serialNumberList"`
	OutputCoinList         []OutputCoin            `protobuf:"bytes,3,rep,name=outputCoinList,proto3" json:"outputCoinList"`
	CommitmentList         []Commitment            `protobuf:"bytes,4,rep,name=commitmentList,proto3" json:"commitmentList"`
	CommitmentIndexList    []CommitmentIndex       `protobuf:"bytes,5,rep,name=commitmentIndexList,proto3" json:"commitmentIndexList"`
	TokenList              []Token                 `protobuf:"bytes,6,rep,name=tokenList,proto3" json:"tokenList"`
	OnetimeAddressList     []OnetimeAddress        `protobuf:"bytes,7,rep,name=onetimeAddressList,proto3" json:"onetimeAddressList"`
	TxPrivacyDataList      []TxPrivacyData         `protobuf:"bytes,8,rep,name=txPrivacyDataList,proto3" json:"txPrivacyDataList"`
	OTACoinList            []OTACoin               `protobuf:"bytes,9,rep,name=oTACoinList,proto3" json:"oTACoinList"`
	OutputCoinSerialNumber *OutputCoinSerialNumber `protobuf:"bytes,10,opt,name=outputCoinSerialNumber,proto3" json:"outputCoinSerialNumber,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7375abeed0ce61dc, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetSerialNumberList() []SerialNumber {
	if m != nil {
		return m.SerialNumberList
	}
	return nil
}

func (m *GenesisState) GetOutputCoinList() []OutputCoin {
	if m != nil {
		return m.OutputCoinList
	}
	return nil
}

func (m *GenesisState) GetCommitmentList() []Commitment {
	if m != nil {
		return m.CommitmentList
	}
	return nil
}

func (m *GenesisState) GetCommitmentIndexList() []CommitmentIndex {
	if m != nil {
		return m.CommitmentIndexList
	}
	return nil
}

func (m *GenesisState) GetTokenList() []Token {
	if m != nil {
		return m.TokenList
	}
	return nil
}

func (m *GenesisState) GetOnetimeAddressList() []OnetimeAddress {
	if m != nil {
		return m.OnetimeAddressList
	}
	return nil
}

func (m *GenesisState) GetTxPrivacyDataList() []TxPrivacyData {
	if m != nil {
		return m.TxPrivacyDataList
	}
	return nil
}

func (m *GenesisState) GetOTACoinList() []OTACoin {
	if m != nil {
		return m.OTACoinList
	}
	return nil
}

func (m *GenesisState) GetOutputCoinSerialNumber() *OutputCoinSerialNumber {
	if m != nil {
		return m.OutputCoinSerialNumber
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "privacy.privacy.GenesisState")
}

func init() { proto.RegisterFile("privacy/genesis.proto", fileDescriptor_7375abeed0ce61dc) }

var fileDescriptor_7375abeed0ce61dc = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcf, 0x4e, 0x1b, 0x31,
	0x10, 0xc6, 0xb3, 0x85, 0xa6, 0xc5, 0xa9, 0xfa, 0xc7, 0xd0, 0xb0, 0x0d, 0xc2, 0x44, 0xbd, 0xc0,
	0x29, 0x51, 0xa9, 0x7a, 0xe9, 0xa9, 0x40, 0xa5, 0x0a, 0xa9, 0x2a, 0x28, 0x50, 0xa9, 0xea, 0xc5,
	0x32, 0x89, 0x15, 0x59, 0xed, 0xae, 0x57, 0xbb, 0x4e, 0xb5, 0xbc, 0x05, 0x8f, 0xc5, 0x91, 0x63,
	0x4f, 0x55, 0x95, 0xbc, 0x08, 0xda, 0xf1, 0x78, 0x77, 0x89, 0x17, 0x4e, 0xb1, 0xfc, 0x7d, 0xdf,
	0x2f, 0xb3, 0x33, 0x63, 0xf2, 0x3a, 0x49, 0xd5, 0x1f, 0x31, 0xbe, 0x1c, 0x4e, 0x65, 0x2c, 0x33,
	0x95, 0x0d, 0x92, 0x54, 0x1b, 0x4d, 0x5f, 0xe0, 0xf5, 0x00, 0x7f, 0x7b, 0x1b, 0x53, 0x3d, 0xd5,
	0xa0, 0x0d, 0x8b, 0x93, 0xb5, 0xf5, 0x36, 0x5c, 0x3a, 0x11, 0xa9, 0x88, 0x30, 0xdc, 0xdb, 0x72,
	0xb7, 0x99, 0x4c, 0x95, 0xf8, 0xcd, 0xe3, 0x59, 0x74, 0x21, 0x53, 0x14, 0xdf, 0x38, 0x51, 0xcf,
	0x4c, 0x32, 0x33, 0x7c, 0xac, 0x55, 0x8c, 0x52, 0xe8, 0xa4, 0xb1, 0x8e, 0x22, 0x65, 0x22, 0x19,
	0x1b, 0x54, 0x98, 0xaf, 0x70, 0x15, 0x4f, 0x64, 0x8e, 0xfa, 0xba, 0xd3, 0x8d, 0xfe, 0x25, 0x1d,
	0x6e, 0xbb, 0xfc, 0xa7, 0x58, 0x1a, 0x15, 0x49, 0x2e, 0x26, 0x93, 0x54, 0x66, 0xd9, 0xb2, 0x6c,
	0x72, 0x8e, 0x47, 0x3e, 0x11, 0x46, 0xa0, 0xdc, 0x2d, 0xd3, 0x46, 0xd4, 0x8b, 0xdc, 0x6d, 0xa8,
	0x9f, 0x37, 0x7c, 0xe8, 0xdb, 0xab, 0x36, 0x79, 0xf6, 0xc5, 0x36, 0xf5, 0xcc, 0x08, 0x23, 0xe9,
	0x07, 0xd2, 0xb6, 0x6d, 0x0a, 0x83, 0x7e, 0xb0, 0xd7, 0xd9, 0xdf, 0x1c, 0x2c, 0x35, 0x79, 0x70,
	0x0a, 0xf2, 0xe1, 0xea, 0xf5, 0xbf, 0x9d, 0xd6, 0x08, 0xcd, 0xf4, 0x84, 0xbc, 0xb4, 0xf8, 0x6f,
	0x40, 0xff, 0xaa, 0x32, 0x13, 0x3e, 0xea, 0xaf, 0xec, 0x75, 0xf6, 0xb7, 0x3d, 0xc0, 0x59, 0xcd,
	0x88, 0x18, 0x2f, 0x4c, 0x8f, 0xc9, 0x73, 0x5b, 0xfb, 0x91, 0x56, 0x31, 0xe0, 0x56, 0x00, 0xb7,
	0xe5, 0xe1, 0x4e, 0x4a, 0x1b, 0xc2, 0x96, 0x82, 0x05, 0xaa, 0x9a, 0x08, 0xa0, 0x56, 0xef, 0x41,
	0x1d, 0x95, 0x36, 0x87, 0xba, 0x1b, 0xa4, 0x3f, 0xc8, 0x7a, 0x75, 0x73, 0x5c, 0xcc, 0x16, 0x78,
	0x8f, 0x81, 0xd7, 0x7f, 0x80, 0x07, 0x5e, 0x84, 0x36, 0x21, 0xe8, 0x47, 0xb2, 0x06, 0x6b, 0x01,
	0xbc, 0x36, 0xf0, 0xba, 0x1e, 0xef, 0xbc, 0x70, 0x20, 0xa5, 0xb2, 0xd3, 0xef, 0x84, 0xe2, 0xf6,
	0x1c, 0xd8, 0xe5, 0x01, 0xc8, 0x13, 0x80, 0xec, 0xf8, 0xfd, 0xba, 0x63, 0x45, 0x5a, 0x03, 0x80,
	0x8e, 0xc8, 0x2b, 0x93, 0x9f, 0xda, 0xd4, 0x67, 0x61, 0x04, 0x50, 0x9f, 0x02, 0x95, 0xf9, 0xa5,
	0xd5, 0x9d, 0x08, 0xf5, 0xe3, 0xf4, 0x13, 0xe9, 0xe8, 0xf3, 0x83, 0x72, 0xa6, 0x6b, 0x40, 0x0b,
	0xfd, 0x1a, 0xad, 0x07, 0x39, 0xf5, 0x08, 0xe5, 0xa4, 0x5b, 0xcd, 0xb7, 0xbe, 0x4a, 0x21, 0x81,
	0x85, 0xdd, 0x7d, 0x60, 0x41, 0xea, 0xf6, 0xd1, 0x3d, 0x98, 0xc3, 0x77, 0xd7, 0x73, 0x16, 0xdc,
	0xcc, 0x59, 0xf0, 0x7f, 0xce, 0x82, 0xab, 0x05, 0x6b, 0xdd, 0x2c, 0x58, 0xeb, 0xef, 0x82, 0xb5,
	0x7e, 0x6e, 0xba, 0x57, 0x95, 0x0f, 0xcb, 0x67, 0x79, 0x99, 0xc8, 0xec, 0xa2, 0x0d, 0x8f, 0xe9,
	0xfd, 0x6d, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xb9, 0x62, 0xcd, 0xa8, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OutputCoinSerialNumber != nil {
		{
			size, err := m.OutputCoinSerialNumber.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if len(m.OTACoinList) > 0 {
		for iNdEx := len(m.OTACoinList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OTACoinList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.TxPrivacyDataList) > 0 {
		for iNdEx := len(m.TxPrivacyDataList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TxPrivacyDataList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.OnetimeAddressList) > 0 {
		for iNdEx := len(m.OnetimeAddressList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OnetimeAddressList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.TokenList) > 0 {
		for iNdEx := len(m.TokenList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TokenList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.CommitmentIndexList) > 0 {
		for iNdEx := len(m.CommitmentIndexList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CommitmentIndexList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.CommitmentList) > 0 {
		for iNdEx := len(m.CommitmentList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CommitmentList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.OutputCoinList) > 0 {
		for iNdEx := len(m.OutputCoinList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OutputCoinList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.SerialNumberList) > 0 {
		for iNdEx := len(m.SerialNumberList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SerialNumberList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.SerialNumberList) > 0 {
		for _, e := range m.SerialNumberList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OutputCoinList) > 0 {
		for _, e := range m.OutputCoinList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CommitmentList) > 0 {
		for _, e := range m.CommitmentList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CommitmentIndexList) > 0 {
		for _, e := range m.CommitmentIndexList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.TokenList) > 0 {
		for _, e := range m.TokenList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OnetimeAddressList) > 0 {
		for _, e := range m.OnetimeAddressList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.TxPrivacyDataList) > 0 {
		for _, e := range m.TxPrivacyDataList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OTACoinList) > 0 {
		for _, e := range m.OTACoinList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.OutputCoinSerialNumber != nil {
		l = m.OutputCoinSerialNumber.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SerialNumberList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SerialNumberList = append(m.SerialNumberList, SerialNumber{})
			if err := m.SerialNumberList[len(m.SerialNumberList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputCoinList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutputCoinList = append(m.OutputCoinList, OutputCoin{})
			if err := m.OutputCoinList[len(m.OutputCoinList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitmentList = append(m.CommitmentList, Commitment{})
			if err := m.CommitmentList[len(m.CommitmentList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentIndexList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitmentIndexList = append(m.CommitmentIndexList, CommitmentIndex{})
			if err := m.CommitmentIndexList[len(m.CommitmentIndexList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenList = append(m.TokenList, Token{})
			if err := m.TokenList[len(m.TokenList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnetimeAddressList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OnetimeAddressList = append(m.OnetimeAddressList, OnetimeAddress{})
			if err := m.OnetimeAddressList[len(m.OnetimeAddressList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxPrivacyDataList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxPrivacyDataList = append(m.TxPrivacyDataList, TxPrivacyData{})
			if err := m.TxPrivacyDataList[len(m.TxPrivacyDataList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OTACoinList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OTACoinList = append(m.OTACoinList, OTACoin{})
			if err := m.OTACoinList[len(m.OTACoinList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputCoinSerialNumber", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OutputCoinSerialNumber == nil {
				m.OutputCoinSerialNumber = &OutputCoinSerialNumber{}
			}
			if err := m.OutputCoinSerialNumber.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
